import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Image from 'next/image'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'PeerCareer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <nav className=" border-gray-300 bg-pink-200 dark:bg-gray-800 dark:border-gray-700">
        <div className="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
          <Image src='/peer-career-logo-cunia1-1@2x.png' alt='PeerCareer LOGO' width={200} height={200} />
          <div className="hidden w-full md:block md:w-auto" id="navbar-solid-bg">
            <ul className="flex flex-col font-medium mt-4 rounded-lg bg-gray-50 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-transparent dark:bg-gray-800 md:dark:bg-transparent dark:border-gray-700">
              <li>
                <a href="#" className="py-2.5 px-3 me-2 mb-2 text-pink-800 hover:text-black text-lg font-semibold flex-col">
                  Home
                </a>
              </li>
              <li>
                <a href="#" className="py-2.5 px-3 me-2 mb-2 text-pink-800 hover:text-black text-lg font-semibold flex-col">
                  Project
                </a>
              </li>
              <li>
                <a href="#" className="py-2.5 px-3 me-2 mb-2 text-pink-800 hover:text-black text-lg font-semibold flex-col">
                  Contact
                </a>               </li>
              <li>
                <a href="#" className="py-2.5 px-3 me-2 mb-2 text-pink-800 hover:text-black text-lg font-semibold flex-col">
                  FAQ
                </a>               </li>
            </ul>
          </div>
        </div>
      </nav>
        {children}
      </body>
    </html>
    
  );
}
